export const COFFEES = [
  {
    id: 1,
    name: "Classic Cappuccino",
    description: "Rich & creamy",
    category: "Cappuccino",
    price: 4.5,
    rating: 4.8,
    image: require("../../assets/project_images/products/classic-cappuccino.webp"),
  },
  {
    id: 2,
    name: "Caramel Cappuccino",
    description: "Sweet & buttery",
    category: "Cappuccino",
    price: 5.25,
    rating: 4.9,
    image: require("../../assets/project_images/products/caramel-cappuccino.webp"),
  },
  {
    id: 3,
    name: "Hazelnut Cappuccino",
    description: "Nutty & smooth",
    category: "Cappuccino",
    price: 5.5,
    rating: 4.7,
    image: require("../../assets/project_images/products/hazelnut-cappuccino.webp"),
  },

  {
    id: 4,
    name: "Classic Latte",
    description: "Smooth & milky",
    category: "Latte",
    price: 4.75,
    rating: 4.8,
    image: require("../../assets/project_images/products/classic-latte.webp"),
  },
  {
    id: 5,
    name: "Vanilla Latte",
    description: "Sweet & aromatic",
    category: "Latte",
    price: 5.25,
    rating: 4.9,
    image: require("../../assets/project_images/products/vanilla-latte.webp"),
  },
  {
    id: 6,
    name: "Caramel Latte",
    description: "Creamy & sweet",
    category: "Latte",
    price: 5.5,
    rating: 4.7,
    image: require("../../assets/project_images/products/caramel-latte.webp"),
  },

  {
    id: 7,
    name: "Single Espresso",
    description: "Bold & intense",
    category: "Espresso",
    price: 2.95,
    rating: 4.6,
    image: require("../../assets/project_images/products/single-espresso.webp"),
  },
  {
    id: 8,
    name: "Double Espresso",
    description: "Strong & robust",
    category: "Espresso",
    price: 3.75,
    rating: 4.8,
    image: require("../../assets/project_images/products/double-espresso.webp"),
  },

  {
    id: 9,
    name: "Classic Mocha",
    description: "Rich & chocolatey",
    category: "Mocha",
    price: 5.5,
    rating: 4.9,
    image: require("../../assets/project_images/products/classic-mocha.webp"),
  },
  {
    id: 10,
    name: "Caramel Mocha",
    description: "Sweet & indulgent",
    category: "Mocha",
    price: 5.95,
    rating: 4.8,
    image: require("../../assets/project_images/products/caramel-mocha.webp"),
  },
  {
    id: 11,
    name: "White Chocolate Mocha",
    description: "Velvety & sweet",
    category: "Mocha",
    price: 6.25,
    rating: 4.8,
    image: require("../../assets/project_images/products/white-chocolate-mocha.webp"),
  },

  {
    id: 12,
    name: "Classic Espresso Macchiato",
    description: "Bold & creamy",
    category: "Macchiato",
    price: 3.95,
    rating: 4.7,
    image: require("../../assets/project_images/products/classic-macchiato.webp"),
  },
  {
    id: 13,
    name: "Caramel Macchiato",
    description: "Sweet & layered",
    category: "Macchiato",
    price: 5.75,
    rating: 4.9,
    image: require("../../assets/project_images/products/caramel-macchiato.webp"),
  },
];
